<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeliveryApp.Modules.Catalog.Domain\DeliveryApp.Modules.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DeliveryApp.BuildingBlocks.Application\DeliveryApp.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DeliveryApp.BuildingBlocks.Domain\DeliveryApp.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
